<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="1" failed="0" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Exception Handled]]>
    </line>
  </reporter-output>
  <suite started-at="2022-04-06T22:51:07 IST" name="Default suite" finished-at="2022-04-06T22:51:07 IST" duration-ms="32">
    <groups>
    </groups>
    <test started-at="2022-04-06T22:51:07 IST" name="Default test" finished-at="2022-04-06T22:51:07 IST" duration-ms="32">
      <class name="TestNG.intr">
        <test-method signature="m1()[pri:0, instance:TestNG.intr@1d119efb]" started-at="2022-04-06T22:51:07 IST" name="m1" finished-at="2022-04-06T22:51:07 IST" duration-ms="5" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Exception Handled]]>
            </line>
          </reporter-output>
        </test-method> <!-- m1 -->
      </class> <!-- TestNG.intr -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
